### ISSUE TITLE
Grapejuice (Wine patch for Roblox on Linux) already has this.

### ISSUE THREAD

**Issue by P3tray** [WaviestBalloon/RobloxFFlagEditor#1]
Feel free to code steal!
![image](https://user-images.githubusercontent.com/31691973/186386747-bbc4de00-0065-4b26-9c95-4c639b32ce1d.png)

You should write this project in Rust like a real chad.

**Comment by WaviestBalloon** [comment]
I give up on Electron honestly, I cannot use it
